### ISSUE TITLE
add more functionalists to the Bot using dialogueFlow

### ISSUE THREAD

**Issue by shantamsultania** [Srimathij/Indra_Bot#10]
hey, 
I am thinking that we can create a responsive API for the which can be made to interact with DialogeFlow and with the help of this API we can make Machine learning models and also add more functionalities to the Bot.

with the help of this we can add things like : 
1. make more accurate predictions 
2. make a small change in the Database or code and new functionality may also get collected for future use cases 
3. can collect the name/ Symptoms that can be used to predict the solutions in future
4. and many more

**Comment by Sibasish-Padhy** [comment]
hey @shantamsultania this looks interesting can i contribute to this issue as a GSSOC participant 2021 and  also give proper guidiance for it if possible...really looking forward to work on it with you

**Comment by shantamsultania** [comment]
hey @Sibasish-Padhy i am not the project admin if the admin approves this functionality we both can work on this together if that's ok with you

**Comment by Sibasish-Padhy** [comment]
yup

**Comment by shantamsultania** [comment]
@Srimathij can you can assign me and @Sibasish-Padhy this issue?

**Comment by alphaX86** [comment]
@shantamsultania @Sibasish-Padhy Hey guys, I'm a mentor of the project, currently PA isn't free coz she's burdened with college classes. Alright, could anyone tell what feature you're gonna add? Based on that, I'll ping PA to review and assign y'all

**Comment by alphaX86** [comment]
@shantamsultania IG you need Dialogflow to do this right? I'm afraid we can't do rn. Maybe how about changing some queries in JSON files?

**Comment by shantamsultania** [comment]
ok i can do it but i need some basic idea from the PA that yes this is the functions she is ok with other wise it will be the same thing again and again that I will be making the API and it will get stuck so if she is available it would be great or we can do it one a discord call I am ok with all

**Comment by alphaX86** [comment]
Main problem is with PA, I don't think she'll respond... Coz I already said the database and didn't ping me back

**Comment by alphaX86** [comment]
Well, call is best IG

**Comment by shantamsultania** [comment]
is there anyone from girl script really looking into this matter as I don't think this is under the rules and regulations of the program I hope all the projects were also told to sign this NOC and all. Cause this is creating an issue they should really look into this and sort this out if PA is not responsive then this project should be removed and all those who raised issues in this projects should be given some points as we were ready to contribute and all but the PA itself is not responsive @alphaX86 if there is any maintainer/ in charge from Girlscript just tag them in this comment also and share this comment to them as I am part-time working also this does make the things a bit slow for me as my week is already planned and if this keeps on coming in other projects also I will not be able to contribute in other projects also #girlsciptIndia #Gssco

**Comment by alphaX86** [comment]
Problem is that I'm the only active maintainer here 🙂 (Sigh)

**Comment by shantamsultania** [comment]
just tell me the names of people to ping related to this on discord will do the same

**Comment by shantamsultania** [comment]
I have shared this issue to the someone named ruchika 

Lets see what she replys 

They should atleast help ypu out as you are taking a time out for this project and mentoring all this is a but unprofessional you also have work right be it clg / office 
@alphaX86

**Comment by alphaX86** [comment]
> just tell me the names of people to ping related to this on discord will do the same

Alright

**Comment by Srimathij** [comment]
Yes you both can do that.
