### ISSUE TITLE
Tech Stack Update ( LOGO add ) 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [Srimathij/Indra_Bot#12]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by alphaX86** [comment]
@rohank2502 you mean Shields badges?

**Comment by alphaX86** [comment]
Or just logos alone?

**Comment by rohan-kulkarni-25** [comment]
Logos only

**Comment by alphaX86** [comment]
Okie assigning you now! xD

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Okie assigning you now! xD

Which tech stack will you like to get added ?

**Comment by alphaX86** [comment]
Here's the tech stack which I analysed (more to come in future) : HTML, CSS, JS and Dialogflow
