### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [Srimathij/Indra_Bot#13]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by alphaX86** [comment]
@rohank2502 that's nice so basically could you explain what you're going to do? Are you going to implement a bot or what?

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> @rohank2502 that's nice so basically could you explain what you're going to do? Are you going to implement a bot or what?

Sorry For delay Not a bot I will add a img tag which will keep updating the contributors list with their avatar in circle (small)

**Comment by alphaX86** [comment]
> > @rohank2502 that's nice so basically could you explain what you're going to do? Are you going to implement a bot or what?
> 
> Sorry For delay Not a bot I will add a img tag which will keep updating the contributors list with their avatar in circle (small)

Interesting.... I'll let you know once I got my maintainer privilege coz the PA isn't free and we're trying to reach her often. If prompted, I'll assign this to you

**Comment by sahilempire** [comment]
I want to work on this issue as a **GSSoC participant**, please a**ssign me**

Thank you

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> > > @rohank2502 that's nice so basically could you explain what you're going to do? Are you going to implement a bot or what?
> > 
> > 
> > Sorry For delay Not a bot I will add a img tag which will keep updating the contributors list with their avatar in circle (small)
> 
> Interesting.... I'll let you know once I got my maintainer privilege coz the PA isn't free and we're trying to reach her often. If prompted, I'll assign this to you

Sure !! No issues !!

**Comment by alphaX86** [comment]
Alright @rohank2502 I'll assign you first. Let's see what you're gonna rock! xD
