### ISSUE TITLE
Improvising Medical Analysis

### ISSUE THREAD

**Issue by codeshruti** [Srimathij/Indra_Bot#14]
Add more diseases/problems and their symptoms. I am a GSSOC'21 Participant

**Comment by alphaX86** [comment]
@codeshruti what kind of feature you're gonna add, explain a bit more

**Comment by codeshruti** [comment]
Adding more usecases for the chatbot, like more diseases and their symptoms.

**Comment by alphaX86** [comment]
Hmm, interesting. So are you willing to take up this issue?

**Comment by codeshruti** [comment]
Yes, that's why I created the issue

**Comment by alphaX86** [comment]
😅 OK ok no problem
