### ISSUE TITLE
Add github action to auto label issues

### ISSUE THREAD

**Issue by Aayush-hub** [Srimathij/Indra_Bot#28]
## Description
Add github action to auto label issues with gssoc21 label when contributor asks to work under gssoc21.

**Comment by Aayush-hub** [comment]
@alphaX86 Currently, the issue template is designed to label every issue with gssoc21 , but what if a contributor who has not participated in GSSoC come to contribute. In that case there is no use of label gssoc21. So, we can edit issue template and add a github action to label issue with gssoc21 whenever contributor asks to work under it.

**Comment by alphaX86** [comment]
@Aayush-hub I think that's a great idea, BTW could you reconfigure or add a new action to label gssoc21? Coz I created an action but it seems to fail every PR

**Comment by Aayush-hub** [comment]
@alphaX86 Sure, will add to auto label for issues and look into what's problem for labeling PR's.

**Comment by alphaX86** [comment]
Well assigning you now..
