### ISSUE TITLE
Make Website Responsive

### ISSUE THREAD

**Issue by Aayush-hub** [Srimathij/Indra_Bot#3]
The website is not supported to mobile view. Make it responsive.

**Comment by Aayush-hub** [comment]
@Srimathij Can you assign me this for GSSoC21 ?

**Comment by Srimathij** [comment]
Hey, the main thing in this project is a chatbot (Indra_A virtual assistant). But you could be able to make conversation with a chatbot.

**Comment by Aayush-hub** [comment]
@Srimathij  In desktop view also the padding is not upto the mark, as first line of message is not fully visible.


![Capture](https://user-images.githubusercontent.com/65889104/110202117-b610af00-7e8c-11eb-91ef-479d0bca33b1.png)

**Comment by alphaX86** [comment]
@Aayush-hub if you try to figure out and make the website correct, can I assign you then?

**Comment by Aayush-hub** [comment]
@alphaX86 Sure!, will try my best

**Comment by alphaX86** [comment]
You're clear @Aayush-hub
