### ISSUE TITLE
Website Responsiveness  and Design

### ISSUE THREAD

**Issue by Avishake007** [Srimathij/Indra_Bot#33]
## What UI bug/error you faced? Could you describe?
The Website is not properly responsive
 I want to work to work on this issue 
please assign me for this issue

**Comment by alphaX86** [comment]
Could you briefly describe what you're gonna do? I mean tasks

**Comment by bhavita2404** [comment]
Can you please be precise what's the issue.

**Comment by Avishake007** [comment]
Actually I am thinking of improving the website responsiveness of the website  and also make few changes like when we see in the smaller devices a hamburger icon will be shown otherwise it will not.

**Comment by Aayush-hub** [comment]
@Avishake007 @alphaX86 Actually the issue is solved by PR #27 . But the code is not pushed to the deployed site (netlify). Kindly run code in your local machine and suggest the further changes that can be made.

**Comment by Avishake007** [comment]
Okay then  I can improve the responsiveness of the website like the logo is not properly positioned for the smaller devices and also on the web page design. Please push the changes on the repo so that I can start working on these issues.

**Comment by alphaX86** [comment]
> Okay then  I can improve the responsiveness of the website like the logo is not properly positioned for the smaller devices and also on the web page design. Please push the changes on the repo so that I can start working on these issues.

That's already pushed IG. So you can start working it. Meanwhile I'll ask admin on this live deploy as she can only do and has the rights
