### ISSUE TITLE
Add about section in website

### ISSUE THREAD

**Issue by Aayush-hub** [Srimathij/Indra_Bot#34]
## What UI bug/error you faced? Could you describe?

We can add a informative about section to the website which can tell users what the project is for and can also celebrate the creators and contributors of this project there.

**Comment by arpit456jain** [comment]
Sir Can I work on this issue

**Comment by arpit456jain** [comment]
I am a Gssoc'21 participant.

**Comment by techpkd123** [comment]
Sir can i work upon this issue as a GSSoC'21 participant?

**Comment by Aayush-hub** [comment]
@techpkd123 @arpit456jain @alphaX86  I am working on it. Kindly give me some time to create a PR.

**Comment by alphaX86** [comment]
Right assigning you @Aayush-hub

**Comment by Varun8216889** [comment]
As a beginner, I want to contribute but I am not able to find the issue.
Can I start my contribution by working on this issue under GSSoC'21? Kindly assign it to me or suggest me one.

**Comment by alphaX86** [comment]
@Varun8216889 to avoid confusion I made a label called "Status:Assigned" which means the Issue is already WIP.

**Comment by alphaX86** [comment]
If the issue is made "Status:Ready for grab" then only you can ask
