### ISSUE TITLE
Lack of Information for user to use the website[CHAT]

### ISSUE THREAD

**Issue by shee35** [Srimathij/Indra_Bot#35]
## Description
presently if any user visits the website, there is not much information available to make it clear how they should use the website. I would like to add Instructions through the chatbot just after the virtual assistant's introduction part. 
## Additional Context
The introduction would include, the necessary things that the chatbot supports, and what the website is meant for along with some examples of how users can start communicating with the assistant.

**Comment by alphaX86** [comment]
@shee35 have you tried seeing the website locally? Coz netlify is broken for now, and we're reaching admin for that

**Comment by shee35** [comment]
No, I haven't seen that locally, I observed this through netlify only. The chat bot keeps on loading in my local, so that was why.

**Comment by alphaX86** [comment]
Oh, alright well better to check this in your local server and then see the problem, coz admin hasn't granted rights to update the site. I'm trying to contact her meanwhile you check this side by side (by cloning repo and seeing)

**Comment by shee35** [comment]
> Oh, alright well better to check this in your local server and then see the problem, coz admin hasn't granted rights to update the site. I'm trying to contact her meanwhile you check this side by side (by cloning repo and seeing)

Yeah, sure!

**Comment by Varun8216889** [comment]
As a beginner, I want to contribute but I am not able to find the issue.
Can I start my contribution by working on this issue under GSSoC'21? Kindly assign it to me or suggest me one.

**Comment by alphaX86** [comment]
@Varun8216889 can I DM you in Discord?

**Comment by Varun8216889** [comment]
@alphaX86 sure

**Comment by alphaX86** [comment]
@Varun8216889 what's your discord ID?

**Comment by Varun8216889** [comment]
Varun(P)#6367

**Comment by Varun8216889** [comment]
devildagar29@gmail.com

**Comment by alphaX86** [comment]
So @shee35 can you take this? If you're free now?

**Comment by shee35** [comment]
Yes Sir, I want to work on it

**Comment by alphaX86** [comment]
> Yes Sir, I want to work on it

I'm not sir 😂 anyway assigning you
