### ISSUE TITLE
feedback form [WEB]

### ISSUE THREAD

**Issue by SuryaSachan** [Srimathij/Indra_Bot#36]
## What UI bug/error you faced? Could you describe?
feedback form is not added

**Comment by SuryaSachan** [comment]
kindly assign this issue to me.

**Comment by alphaX86** [comment]
Hey there, have you tried running this repo in your local system. Coz Netlify one is a bit broken and need to be updated (only admin can do not us)

**Comment by SuryaSachan** [comment]
Yes, index.html  differ from the Deployed  website

**Comment by alphaX86** [comment]
Hmm, alright. Ready to take this one? Assigning you now...

**Comment by SuryaSachan** [comment]
yes, thanks a lot.

**Comment by alphaX86** [comment]
@SuryaSachan what's the status?

**Comment by alphaX86** [comment]
@SuryaSachan this is a warning here, if you take more days, then I have to assign someone else

**Comment by SuryaSachan** [comment]
@alphaX86  my apologies for delayed response. Can you tell in which mail address I have to notify in case of any feedback received in form. Rest of the feedback form  is complete. Thank you

**Comment by alphaX86** [comment]
Hmm, I didn't think of this! Maybe you can use uh.... admin's email here it is.... srimathijagadeesan51@gmail.com

**Comment by alphaX86** [comment]
You can use IG

**Comment by SuryaSachan** [comment]
thank you , I will create PR today

**Comment by SuryaSachan** [comment]
Kindly review PR #47

**Comment by alphaX86** [comment]
One sec... reviewing

**Comment by SuryaSachan** [comment]
I am not sure how to add another  item in drop down navigation bar. Therefore I placed it in place of "Home". So that it can be viewed temporarily.
