### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Aayush-hub** [Srimathij/Indra_Bot#38]
@alphaX86 Just a suggestion for a feature, can we add a github icon linked to this github repository in about page so that if anyone come through website and find a bug then he/she can be redirected to this repo and can create a issue or work on it.
What's your idea about it?

**Comment by alphaX86** [comment]
This is great I'd say

**Comment by Aayush-hub** [comment]
@alphaX86 Can I work on it?

**Comment by alphaX86** [comment]
This is Level0 though..... I have a person who's asking for good first issues. Maybe I can give him a chance, so that he can work upon. Only this issue

**Comment by alphaX86** [comment]
@Varun8216889 are you ready to take this one? This is a simple task :)

**Comment by Varun8216889** [comment]
yeah sure, but what specifically I have to do.
please guide.

**Comment by Aayush-hub** [comment]
@alphaX86 Sure! @Varun8216889 Good luck, Happy coding :)

**Comment by Aayush-hub** [comment]
@Varun8216889 You have just to add a github icon in about page on bottom right and link it to this repository.

**Comment by Varun8216889** [comment]
ok thanks for guiding me. Kindly assign it to me.

**Comment by alphaX86** [comment]
@Varun8216889 you're good to go. Good luck!

**Comment by Varun8216889** [comment]
@alphaX86  Can We add a small feature that when anyone opens your social media handle by clicking on icons on the about page then it should open in a different tab.

**Comment by alphaX86** [comment]
Great! IG you can add it too. And one thing I forgot. Run your site locally, don't use the Netlify site. It's broken and Admin isn't responding to that. So, try to run it locally and make the changes :)

**Comment by alphaX86** [comment]
Issue fixed via #40
