### ISSUE TITLE
Text to Speech coverter

### ISSUE THREAD

**Issue by iaditichine** [Srimathij/Indra_Bot#39]
Hey,I am a GSSOC'21 student,I want to contribute code for Text to Speech converter using python along with a proper readme.md file explaining the process. Please assign this issue to me.
Thank you!

**Comment by alphaX86** [comment]
@iaditichine describe what you're gonna do. Plus, the issue you opened is an important one

**Comment by iaditichine** [comment]
Using gTTs API, I am going to convert entered text into . mp3 file. gTTs supports different language but I'm going use English language as of now.

**Comment by alphaX86** [comment]
Hmm, alright. So how many days you need for this?

**Comment by iaditichine** [comment]
One day

**Comment by alphaX86** [comment]
Alright! Assigning you for this...

**Comment by iaditichine** [comment]
In which folder should I add my files?

**Comment by alphaX86** [comment]
You can create a separate folder for it :)

**Comment by alphaX86** [comment]
Issue downgrading to Level 3 and Level 2. Closing this as it's solved via PR #42

**Comment by iaditichine** [comment]
According to new marking scheme, I should get 25 points for level 2 issue
but I got only 15 points.

**Comment by alphaX86** [comment]
Oh ok, report this to the organisers, maybe I think they'll help. IG they stuck to last marking scheme

**Comment by iaditichine** [comment]
Okay
