### ISSUE TITLE
Add MIT License

### ISSUE THREAD

**Issue by Akash20x** [Srimathij/Indra_Bot#4]
Please assign me this issue as a part of GSSoC'21

**Comment by anurag0singh** [comment]
This PR request is created under GSSOC'21. Please treat it likely if possible at all. @Srimathij

**Comment by Akash20x** [comment]
@anurag0singh the project maintainer doesn't check this issue and didn't assign anyone for the issue nor add any labels.

Always send pull request when project maintainer assign you. By the way I am not project maintainer and open this issue as GSSoC'21 participant to assign me to do this task .

**Comment by anurag0singh** [comment]
Ok cool.
I don't have any problem if this gets assigned to you.
Happy coding 😁
@Akash20x

**Comment by alphaX86** [comment]
@anurag0singh @Akash20x  if you're creating a license, please always mention the name of the project owner and not yours. Due to such case, I had to close one PR 😞

**Comment by alphaX86** [comment]
@Akash20x are you ready to take this issue?

**Comment by Akash20x** [comment]
> @Akash20x are you ready to take this issue?

Yes

**Comment by alphaX86** [comment]
You're ready to go

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by alphaX86** [comment]
Done! @Akash20x
