### ISSUE TITLE
Favicon is to be added[WEB]

### ISSUE THREAD

**Issue by SuryaSachan** [Srimathij/Indra_Bot#48]
## What UI bug/error you faced? Could you describe?

website icon is to be added in all pages

**Comment by alphaX86** [comment]
@SuryaSachan right! So, any suggestions for Favicons? Maybe I can take a look

**Comment by SuryaSachan** [comment]
![image](https://user-images.githubusercontent.com/58931486/113505297-7c9a9480-955b-11eb-877d-ceebe283b7ce.png)
May be something like this can work

**Comment by SuryaSachan** [comment]
we can use  
https://github.com/Srimathij/Indra_Bot/blob/main/logo.jpg

**Comment by SuryaSachan** [comment]
kindly assign me this issue

**Comment by alphaX86** [comment]
Alright

**Comment by alphaX86** [comment]
> ![image](https://user-images.githubusercontent.com/58931486/113505297-7c9a9480-955b-11eb-877d-ceebe283b7ce.png)
> May be something like this can work

Interesting

**Comment by alphaX86** [comment]
Solved via #52
