### ISSUE TITLE
[DOC] Capitalize and correct letters in DatabaseConnection/README 

### ISSUE THREAD

**Issue by alphaX86** [Srimathij/Indra_Bot#49]
## Description

Recently @shantamsultania and I have discussed about Database connection for this project a long time back, so it took some time but finally the feature is added (as a demo) but the documentation is a bit non-grammatical. So some instructions may need to be refined.

## Additional context
Just capitalize some letters or even add instructions to your understanding. I'll review and check it

**Comment by alphaX86** [comment]
@Varun8216889 are you ready to take up this? This won't take a long time

**Comment by alphaX86** [comment]
If you're interested I'll assign you in morning, you can work side by side until then

**Comment by shantamsultania** [comment]
You can take it varun @alphaX86 u can assign it to him

**Comment by alphaX86** [comment]
Hmm alright @Varun8216889 you're in

**Comment by alphaX86** [comment]
Well I guess he needs to comment only then I can assign him

**Comment by shantamsultania** [comment]
And again sorry for grammatical mistakes

**Comment by alphaX86** [comment]
It's OK, bugs are opportunities :)

**Comment by Varun8216889** [comment]
yeah, I love to work on this issue. plz assign it to me
