### ISSUE TITLE
Speech to Text converter

### ISSUE THREAD

**Issue by iaditichine** [Srimathij/Indra_Bot#54]
Hello,I am GSSoC '21 participant and I would like to contribute code for Speech to Text conversion using python along with a proper readme.md file explaining the code. Please assign this issue to me.

**Comment by alphaX86** [comment]
Explain the concept brief here and I hope it's not like last time doing only sample

**Comment by iaditichine** [comment]
Using Speech Recognition library in python,I will convert audio file into a text file.

**Comment by iaditichine** [comment]
And live audio into text.

**Comment by alphaX86** [comment]
Hmm, ok. You can do this then.

**Comment by alphaX86** [comment]
Remember I'll check and implement this time

**Comment by alphaX86** [comment]
@iaditichine Hey if you need to do this, please do it fast (coz this project will be considered inactive in few days due to PA and I'll be shifted towards other project)

**Comment by iaditichine** [comment]
Why inactive? I'll be needing 2-3 days because my exams are going on.

**Comment by alphaX86** [comment]
I didn't consider inactive, GSSoC considered.... all because of PA's inactivity. Hmm, in that case, just do a PR when you're free, I'll merge it

**Comment by alphaX86** [comment]
And all inactive projects mentors (which includes me) will be shifted towards some other projects, don't ask GSSoC about this coz it's under progress. That's why I'm telling this before hand

**Comment by iaditichine** [comment]
Okay
