### ISSUE TITLE
Modifying /Styling Readme.md file

### ISSUE THREAD

**Issue by DOOMSTERR** [Srimathij/Indra_Bot#55]
# Proposed Changes
### Modifying by adding 

1.)Adding Shield batches in different colors (at center-top):
-> issues-open
-> pull_request-open
-> total no. of forks
-> total no. of stars

2.)Adding emojis and changing alignments of some 
headings/text to make it look better.

3.)Adding Sections:
->In Contributor Section adding
>Project Manager/Admin Section

Hello, @Srimathij, Please assign me this issue under the GSSOC21 label and Levels label.

Thank You.

**Comment by alphaX86** [comment]
This is great! I also thought of adding shields.io badges, glad you reminded

**Comment by alphaX86** [comment]
You're in @DOOMSTERR 🥳

**Comment by alphaX86** [comment]
@DOOMSTERR please make a PR fast

**Comment by DOOMSTERR** [comment]
PR Generated sorry for the late PR was stuck with some work.
