### ISSUE TITLE
[DOC] update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [Srimathij/Indra_Bot#56]
Hi! I would like to add the following in contributing.md-
Difference between GIT and GITHUB
How to clone,fork repository
How to create a branch and then use git push to push to repo
Create a PR
Squash commits in a single issue into one
Updating the forked and local repo as the updations are made in the upstream

**Comment by alphaX86** [comment]
Alright, you're in

**Comment by khareyash05** [comment]
@alphaX86 Created a PR Have a look
