### ISSUE TITLE
add CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by starlightknown** [Srimathij/Indra_Bot#6]
please add code of conduct to maintain the guidelines for contributions

**Comment by anurag0singh** [comment]
Assign me under GSSOC'21

**Comment by alphaX86** [comment]
@kcoder63 What kind of CODE_OF_CONDUCT you're gonna propose? Contributor Covenant? Or some other?

**Comment by gaulghost** [comment]
Participants, please follow these rules. 

1.You need to be already registered for GSSoC '21.

2.Can't register right now again.

3.Comment on a particular issue to get it assigned to you. 

4. Try to explain your approach to solve any issue in the comments. This will increase the chances of you being assigned. 

5. Don't create issues that are already listed. 

6. Please don't pick up an issue already assigned to someone else. Work on the issues after get  assigned to you 

7. Make sure you discuss in Discord before working on the issue.

8. If any issue is assigned to you, make sure you complete it before the deadline.

9.
Deadline for issues:
Level0 - level1:  days
Level2:  days
Level3: _ days
If you fail to make a PR within the deadline, then the issue will be assigned to another person in the queue.

10. While making PRs, don't forget to add a description and screenshots of your work.

11. Make sure your solution to any issue is better in terms of performance and other parameters in comparison to the previous work.

Can you please review it and let me know they are enough or anything to add? or anything to remove from the list?

Is this the write-up you want?
I am working for first time so have not much idea... But above are some of the points mentioned during introduction meet

**Comment by alphaX86** [comment]
@gaulghost that belongs to a part of CONTRIBUTING.md, by default GitHub has already a template for creating Code Of Conduct! Oh, if you don't know this fact. I'll provide a link then. That's more than enough

**Comment by alphaX86** [comment]
Here it is [Link](https://docs.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project)

Just refer and comeback. It'll give an idea

**Comment by gaulghost** [comment]
Thanks for the information :) @alphaX86

**Comment by alphaX86** [comment]
So who's gonna take this? I'm really confused here! 😅😂

**Comment by alphaX86** [comment]
@kcoder @gaulghost @anurag0singh who's gonna take this?

**Comment by aelbasioni** [comment]
Ready to take it @alphaX86

**Comment by alphaX86** [comment]
Great, I suppose it'll take a day
