### ISSUE TITLE
[DOC] Contributors section bug in readme

### ISSUE THREAD

**Issue by Aayush-hub** [Srimathij/Indra_Bot#61]
## Description

Contributors to this project is not rendered in readme. Plus readme not looking good with large images in project admin section.

**Comment by Aayush-hub** [comment]
@alphaX86 Can I look into the bug?

**Comment by alphaX86** [comment]
Look it asap. I'll merge it today itself as GSSoC considered as inactive repo (all because of PA inactivity)
