### ISSUE TITLE
[Feature] Deploy Website on Github Pages

### ISSUE THREAD

**Issue by Aayush-hub** [Srimathij/Indra_Bot#63]
## What UI bug/error you faced? Could you describe?

Deploy Website on  github pages because netlify link is broken. This will help contributors to check the recent changes live and plan further features accordingly.
## Additional details

Sample deployment link deployed by me on Github pages : https://aayush-hub.github.io/Indra_Bot/

**Comment by Aayush-hub** [comment]
@alphaX86 What are your views on it?

**Comment by alphaX86** [comment]
Wow you're the only person to make a contribution after merging a PR lol 😂😂

**Comment by alphaX86** [comment]
I mean in terms of speed

**Comment by alphaX86** [comment]
Looks good, but IDK if GitHub pages are required... then PA has the access to it. Not me. I'll ask a Q @Aayush-hub how will you update every time on your repo when changes are made here? I also tried your method but felt really hard. I even tried to automate but it's a bit skeptical

**Comment by Aayush-hub** [comment]
@alphaX86 Yes I cannot update the changes everytime 😂😂. But you can deploy it. Go to project settings>Pages>set source as main>press save.

![Capture](https://user-images.githubusercontent.com/65889104/114509728-7f7c4000-9c53-11eb-89bd-aed3f2d310ad.JPG)

**Comment by alphaX86** [comment]
Ok, I know that but see this dude @Aayush-hub 
![image](https://user-images.githubusercontent.com/59508546/114509931-b5b9bf80-9c53-11eb-80f8-3d8199d40200.png)

**Comment by alphaX86** [comment]
There's no settings for me as I'm just a collaborator LOL

**Comment by alphaX86** [comment]
Maybe I can consider it as impossible coz PA is really inactive and last contacted is a month ago

**Comment by alphaX86** [comment]
What do you say?

**Comment by Aayush-hub** [comment]
> Maybe I can consider it as impossible coz PA is really inactive and last contacted is a month ago

@alphaX86 Yes, I also think so. I thought you have access to this. But now it cannot be done.

**Comment by alphaX86** [comment]
Alright, closing this then
