### ISSUE TITLE
Readme file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [Srimathij/Indra_Bot#64]
The Readme file can be enhanced by adding a list of Open Source programs in which this project has been listed in. Also there are a lot of grammatical errors that needs correction.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by alphaX86** [comment]
IDK if GSSoC accepts this coz they considered this project as stale due to severe inactivity of project admin.... So @anirudhsai20 ask GSSoC team if they accept PRs if so you can do

**Comment by alphaX86** [comment]
Project has become stale due to inactivity of PA, GSSoC organisers removed this project :( Sorry. Closing this
