### ISSUE TITLE
Greeting bot

### ISSUE THREAD

**Issue by anurag0singh** [Srimathij/Indra_Bot#8]
Adding a greeting bot to the repo that will greet everyone who creates a PR or opens an issue on this repo.

Please assign me under GSSOC'21.

**Comment by sudhansukinng** [comment]
@anurag0singh  pleases assign this issue to me. I would like to work on this.,

**Comment by thesakshipandey** [comment]
Please assign this issue to me, I'll be able to do this, bc I've done this in my website

**Comment by anurag0singh** [comment]
@sudhansukinng @thesakshipandey I have opened this issue because I want to work on this. You can have the project if they assign any one of you.

**Comment by alphaX86** [comment]
Calm down people, basically you're gonna implement GitHub Actions. Am I right? BTW I'm a mentor of the project

**Comment by alphaX86** [comment]
So, @thesakshipandey @sudhansukinng who's ready to take this one?

**Comment by sudhansukinng** [comment]
I will work on this @alphaX86.

**Comment by alphaX86** [comment]
You're good to go @sudhansukinng

**Comment by sudhansukinng** [comment]
Thank you for assigning this to me. @alphaX86.

**Comment by alphaX86** [comment]
What's the status @sudhansukinng is it over?

**Comment by alphaX86** [comment]
If you're not complying I'll assign to someone else... Do look at it

**Comment by sudhansukinng** [comment]
@alphaX86 sorry for the delay. I was stuck in other issues. I will submit my work till tomorrow evening.

**Comment by alphaX86** [comment]
Alright make sure you do on time, coz Level0 issues are easy and won't take much time

**Comment by sudhansukinng** [comment]
Okey

**Comment by alphaX86** [comment]
This is beyond time limit, un assigning you now

**Comment by aayushirai9900** [comment]
@alphaX86  Can you assign this issue to me

**Comment by alphaX86** [comment]
You have one day to fix this @aayushirai9900

**Comment by alphaX86** [comment]
If you have doubts, reach out to me or refer the net
