### ISSUE TITLE
modifying Home Page 🚀🚀!

### ISSUE THREAD

**Issue by bhubesh757** [Srimathij/Indra_Bot#9]
adding Some Cool Lotties to the Homepage and Adding a Footer with some social Media links with awesome css 
@Srimathij Kindly ,  assign this to me I will share the ui in Discord

**Comment by alphaX86** [comment]
@bhubesh757 I'm sorry for late reply, but what kind of UI can I expect?

**Comment by GurshehzadSingh** [comment]
im a gssoc participant and i would like to work on this isuue..we can add a dark mode and a smooth scrolling feature

**Comment by bhubesh757** [comment]
> @bhubesh757 I'm sorry for late reply, but what kind of UI can I expect?

@alphaX86 I will Make the webpage more clean and looks pretty , i will send you the ui design! plase look into it , using react js , styled components please assign it to me

**Comment by alphaX86** [comment]
> im a gssoc participant and i would like to work on this isuue..we can add a dark mode and a smooth scrolling feature

Hmm dark mode..... Well, open a separate issue and ping me, I'll look at it @GurshehzadSingh :)

**Comment by alphaX86** [comment]
@bhubesh757 send in the UI design once you done, until then it's open

**Comment by GurshehzadSingh** [comment]
Cool.. let me open the issue..u can see the functionality of the dark mode which i want to implement on my portfolio website. just click on the toggle button: https://gurshehzad-singh-portfolio.netlify.app

**Comment by alphaX86** [comment]
@GurshehzadSingh this is really nice. I mean the dark mode toggle is really cool! I think it's great to implement this

**Comment by Aayush-hub** [comment]
@alphaX86 Can I work on adding footer to website having some social links

**Comment by alphaX86** [comment]
Sure thing, so can I consider this as a collab type? In such case, this issue stays open

**Comment by alphaX86** [comment]
The home page is almost modified. IG I can close this for now... If any feature needs to be added, open a new issue and chat there
